{{- if .Values.ingress.basicAuth.enabled -}}
apiVersion: v1
kind: Secret
type: Opaque
data:
  auth: {{ .Values.ingress.basicAuth.auth | b64enc }}
metadata:
  name: {{ include "lwt-chart.fullname" . }}-basic-auth
{{- end }}
